# Generated by Django 4.1 on 2023-11-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_students_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
