# Generated by Django 4.1 on 2023-12-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeronline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeronline',
            name='email',
            field=models.CharField(max_length=300),
        ),
    ]
